"""
-------------------------------------------------------
Stripe payments (hosted Checkout)
-------------------------------------------------------
All amounts coming from the client are IGNORED. Prices are always
recomputed from the ticket_types table so the customer can never set
their own price. Everything runs against Stripe Test Mode.
-------------------------------------------------------
"""

import stripe
from django.conf import settings
from django.utils import timezone

from .models import Bookings, Payments, TicketTypes

stripe.api_key = settings.STRIPE_SECRET_KEY


class PaymentError(Exception):
    """Raised when a checkout request is invalid (bad event/ticket/quantity)."""
    pass


"""
    -------------------------------------------------------
    Builds Stripe line items from the requested tickets, pricing
    everything from the database (never from the client).
    Use: line_items, total = compute_line_items(event_id, tickets)
    -------------------------------------------------------
    Parameters:
        event_id - id of the event being booked - int
        tickets  - list of {"type_id": int, "quantity": int} - list
    Returns:
        line_items - Stripe line_items list - list
        total      - total price in dollars - Decimal
    ------------------------------------------------------
"""
def compute_line_items(event_id, tickets):
    if not tickets:
        raise PaymentError("No tickets selected.")

    line_items = []
    total = 0

    for item in tickets:
        type_id = item.get("type_id")
        quantity = item.get("quantity", 0)

        if not isinstance(quantity, int) or quantity < 1:
            raise PaymentError("Ticket quantity must be at least 1.")

        try:
            ticket_type = TicketTypes.objects.get(type_id=type_id)
        except TicketTypes.DoesNotExist:
            raise PaymentError(f"Unknown ticket type: {type_id}.")

        if ticket_type.event_id != event_id:
            raise PaymentError("Ticket type does not belong to this event.")

        total += ticket_type.price * quantity
        line_items.append({
            "quantity": quantity,
            "price_data": {
                "currency": "cad",
                # Stripe expects the amount in cents (smallest currency unit).
                "unit_amount": int(ticket_type.price * 100),
                "product_data": {
                    "name": f"{ticket_type.event.event_name} — {ticket_type.tier}",
                },
            },
        })

    return line_items, total


"""
    -------------------------------------------------------
    Creates an unconfirmed booking row to attach the payment to.
    Seat / individual ticket rows are generated by the booking
    feature on confirmation and are intentionally out of scope here.
    Use: booking = create_pending_booking(user, event_id)
    -------------------------------------------------------
    Parameters:
        user     - the logged-in buyer - Users
        event_id - id of the event being booked - int
    Returns:
        booking - the created Bookings row - Bookings
    ------------------------------------------------------
"""
def create_pending_booking(user, event_id):
    return Bookings.objects.create(
        requested_at=timezone.now(),
        confirmed=False,
        user=user,
        event_id=event_id,
    )


"""
    -------------------------------------------------------
    Creates a Stripe Checkout Session for a pending booking and
    records a pending payment row.
    Use: session = create_checkout_session(booking, line_items, total, success_url, cancel_url)
    -------------------------------------------------------
    Parameters:
        booking     - the pending Bookings row - Bookings
        line_items  - Stripe line_items list - list
        total       - total price in dollars - Decimal
        success_url - where Stripe sends the user after paying - str
        cancel_url  - where Stripe sends the user if they cancel - str
    Returns:
        session - the Stripe Checkout Session - stripe.checkout.Session
    ------------------------------------------------------
"""
def create_checkout_session(booking, line_items, total, success_url, cancel_url):
    session = stripe.checkout.Session.create(
        mode="payment",
        line_items=line_items,
        success_url=success_url,
        cancel_url=cancel_url,
        metadata={"booking_id": booking.booking_id},
    )

    Payments.objects.create(
        booking=booking,
        stripe_session_id=session.id,
        amount=total,
        currency="cad",
        status="pending",
    )

    return session


"""
    -------------------------------------------------------
    Checks a Checkout Session with Stripe and, if it is paid,
    marks the payment and its booking as confirmed. Safe to call
    more than once (idempotent).
    Use: status, booking_id = mark_paid(session_id)
    -------------------------------------------------------
    Parameters:
        session_id - the Stripe Checkout Session id - str
    Returns:
        status     - the payment status ("paid" or otherwise) - str
        booking_id - the related booking id (or None) - int
    ------------------------------------------------------
"""
def mark_paid(session_id):
    session = stripe.checkout.Session.retrieve(session_id)

    try:
        payment = Payments.objects.get(stripe_session_id=session_id)
    except Payments.DoesNotExist:
        raise PaymentError("Unknown payment session.")

    if session.payment_status == "paid":
        payment.status = "paid"
        payment.stripe_payment_intent = session.payment_intent
        payment.save()

        booking = payment.booking
        booking.confirmed = True
        booking.save()

    return session.payment_status, payment.booking_id
