# Generated by Django 6.0.6 on 2026-06-20 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField()),
                ('confirmed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=63, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TicketTypes',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('tier', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'ticket_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('cancellation_window_hours', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'upcoming_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('venue_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_address', models.CharField(max_length=1000)),
                ('province', models.CharField(blank=True, max_length=2, null=True)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'venues',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.CharField(max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.bookings')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.tickettypes')),
            ],
            options={
                'db_table': 'tickets',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tickettypes',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.upcomingevents'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.upcomingevents'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=127)),
                ('forename', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('pass_field', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.roles')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='upcomingevents',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.users'),
        ),
        migrations.CreateModel(
            name='EventPerformers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.upcomingevents')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.users')),
            ],
            options={
                'db_table': 'event_performers',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.users'),
        ),
        migrations.AddField(
            model_name='upcomingevents',
            name='venue',
            field=models.ForeignKey(db_column='venue', on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.venues'),
        ),
        migrations.CreateModel(
            name='PerformerLinks',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='performerlinks_manager_set', to='authapp.users')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.users')),
            ],
            options={
                'db_table': 'performer_links',
                'managed': True,
                'unique_together': {('performer', 'manager')},
            },
        ),
    ]
