# Generated by Django 6.0.6 on 2026-06-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventPerformers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='requested', max_length=20)),
            ],
            options={
                'db_table': 'event_performers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='cad', max_length=3)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerformerLinks',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'performer_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=63, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketTypes',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('tier', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ticket_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('cancellation_window_hours', models.IntegerField(default=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'upcoming_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=127, null=True)),
                ('forename', models.CharField(blank=True, max_length=127, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('venue_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_address', models.CharField(max_length=1000)),
                ('province', models.CharField(blank=True, max_length=2, null=True)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'venues',
                'managed': False,
            },
        ),
    ]
